global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_api"
    static_configs:
      - targets: ["express_api:3000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
`